export default function Page() {
    return (
        <div className="min-h-screen bg-[color:var(--background)] px-4 py-6 text-[color:var(--foreground)] sm:px-6 sm:py-8">
            <section className="mx-auto grid max-w-3xl gap-4 border border-[color:var(--border)] bg-[color:var(--panel)] p-6">
                <p className="m-0 font-mono text-[11px] uppercase tracking-[0.08em] text-[color:var(--muted)]">
                    Generated by Better Agent
                </p>
                <h1 className="m-0 text-[1.85rem] font-semibold tracking-[-0.05em] text-white sm:text-[2.2rem]">
                    Next.js starter
                </h1>
                <p className="m-0 text-sm leading-7 text-[color:var(--muted)]">
                    Better Agent is wired in. Add your own UI or rerun create with the starter UI
                    enabled.
                </p>
            </section>
        </div>
    );
}
