<script setup lang="ts">
import { useAgent } from "@better-agent/client/vue";
import { ref } from "vue";
import { client } from "~~/lib/better-agent/client";

const input = ref("");
const agent = useAgent(client, {
    agent: "anthropic",
    conversationId: "main",
    hydrateFromServer: true,
    resume: true,
});

const send = async () => {
    if (agent.status.value === "submitted" || agent.status.value === "streaming") {
        agent.stop();
        return;
    }

    const value = input.value.trim();
    if (!value) return;
    input.value = "";
    await agent.sendMessage(value);
};
</script>

<template>
  <main class="min-h-screen bg-[color:var(--background)] px-4 py-6 text-[color:var(--foreground)] sm:px-6 sm:py-8">
    <section class="mx-auto grid max-w-3xl gap-4">
      <header class="grid gap-3">
        <p class="m-0 font-mono text-[11px] uppercase tracking-[0.08em] text-[color:var(--muted)]">
          Generated by Better Agent
        </p>
        <h1 class="m-0 text-[1.85rem] font-semibold tracking-[-0.05em] text-white sm:text-[2.2rem]">
          Nuxt Starter Chat
        </h1>
        <div class="flex items-center gap-2 border border-[color:var(--border)] bg-[color:var(--panel)] px-3 py-2 font-mono text-[11px] uppercase tracking-[0.2em] text-[color:var(--muted)]">
          <span class="text-white/55">&gt;_</span>
          <span class="text-white/78">/agents/openai</span>
        </div>
      </header>

      <section class="grid gap-3 border border-[color:var(--border)] bg-[color:var(--panel)] p-3 sm:p-4">
        <div class="flex items-center justify-between gap-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[color:var(--muted)]">
          <span>conversation main</span>
          <span>{{ agent.status.value }}</span>
        </div>

        <section class="grid min-h-[320px] gap-3 border border-[color:var(--border)] bg-[color:var(--panel-muted)] p-3" aria-live="polite">
          <div v-if="agent.messages.value.length === 0" class="grid place-items-center border border-dashed border-[color:var(--border)] px-4 py-12 text-center text-sm leading-6 text-[color:var(--muted)]">
            No messages yet.
          </div>
          <div v-else class="grid content-start gap-3 self-start">
            <article v-for="message in agent.messages.value" :key="message.localId" :class="`max-w-[88%] border px-2.5 py-2 text-sm leading-[1.55] ${message.role === 'user' ? 'ml-auto border-[color:var(--border-strong)] bg-white text-black' : 'border-[color:var(--border)] bg-black text-[color:var(--foreground)]'}`">
              <p :class="`m-0 font-mono text-[9px] uppercase tracking-[0.18em] ${message.role === 'user' ? 'text-black/55' : 'text-[color:var(--muted)]'}`">
                {{ message.role }}
              </p>
              <p class="m-0 mt-1.5 whitespace-pre-wrap">{{ message.parts.filter((part) => part.type === "text").map((part) => part.text).join("\n") || "No text content" }}</p>
            </article>
          </div>
        </section>

        <form class="grid gap-3" @submit.prevent="void send()">
          <textarea v-model="input" placeholder="Ask something..." aria-label="Message" class="min-h-[96px] w-full resize-none border border-[color:var(--border)] bg-black px-3 py-2.5 text-sm leading-6 text-[color:var(--foreground)] outline-none transition placeholder:text-[color:var(--muted)] focus:border-[color:var(--border-strong)]" />
          <div class="flex flex-wrap items-center justify-end gap-3">
            <div class="flex items-center gap-2">
              <button type="button" @click="agent.stop()" :disabled="agent.status.value !== 'submitted' && agent.status.value !== 'streaming'" class="border border-[color:var(--border)] px-3 py-2 text-sm text-[color:var(--foreground)] transition hover:border-[color:var(--border-strong)] disabled:cursor-not-allowed disabled:opacity-40">Stop</button>
              <button type="submit" :disabled="agent.status.value === 'submitted' || agent.status.value === 'streaming' || input.trim().length === 0" class="border border-white bg-white px-3 py-2 text-sm font-medium text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-40">{{ agent.status.value === "streaming" || agent.status.value === "submitted" ? "Streaming" : "Send" }}</button>
            </div>
          </div>
          <p v-if="agent.error.value" class="m-0 border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">{{ agent.error.value.message }}</p>
          <div class="border-t border-[color:var(--border)] pt-3">
            <p class="m-0 font-mono text-[10px] uppercase tracking-[0.18em] text-[color:var(--muted)]">
              Docs
              <a href="https://www.better-agent.com/docs" target="_blank" rel="noreferrer" class="font-medium text-white/88">better-agent.com/docs</a>
            </p>
          </div>
        </form>
      </section>
    </section>
  </main>
</template>
