import { z } from "zod";

export const OpenAIImageModels = z.enum([
    "dall-e-2",
    "dall-e-3",
    "gpt-image-1",
    "gpt-image-1-mini",
]);

export type OpenAIImageModels = z.infer<typeof OpenAIImageModels>;

export const OpenAICreateImageSchema = z.object({
    prompt: z
        .string()
        .describe(
            "A text description of the desired image(s). The maximum length is 32000 characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.",
        ),
    model: z
        .union([z.string(), OpenAIImageModels])
        .describe(
            "The model to use for image generation. One of `dall-e-2`, `dall-e-3`, or `gpt-image-1`. Defaults to `dall-e-2` unless a parameter specific to `gpt-image-1` is used.",
        )
        .optional(),
    n: z
        .number()
        .int()
        .gte(1)
        .lte(10)
        .describe(
            "The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.",
        )
        .default(1),
    quality: z
        .enum(["standard", "hd", "low", "medium", "high", "auto"])
        .describe(
            "The quality of the image that will be generated.\n\n- `auto` (default value) will automatically select the best quality for the given model.\n- `high`, `medium` and `low` are supported for `gpt-image-1`.\n- `hd` and `standard` are supported for `dall-e-3`.\n- `standard` is the only option for `dall-e-2`.\n",
        )
        .default("auto"),
    response_format: z
        .enum(["url", "b64_json"])
        .describe(
            "The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for `gpt-image-1` which will always return base64-encoded images.",
        )
        .default("url"),
    output_format: z
        .enum(["png", "jpeg", "webp"])
        .describe(
            "The format in which the generated images are returned. This parameter is only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.",
        )
        .default("png"),
    output_compression: z
        .number()
        .int()
        .describe(
            "The compression level (0-100%) for the generated images. This parameter is only supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and defaults to 100.",
        )
        .default(100),
    stream: z
        .boolean()
        .describe(
            "Generate the image in streaming mode. Defaults to `false`. See the\n[Image generation guide](https://platform.openai.com/docs/guides/image-generation) for more information.\nThis parameter is only supported for `gpt-image-1`.\n",
        )
        .default(false),
    partial_images: z
        .union([
            z
                .number()
                .int()
                .gte(0)
                .lte(3)
                .describe(
                    "The number of partial images to generate. This parameter is used for\nstreaming responses that return partial images. Value must be between 0 and 3.\nWhen set to 0, the response will be a single image sent in one streaming event.\n\nNote that the final image may be sent before the full number of partial images\nare generated if the full image is generated more quickly.\n",
                )
                .default(0),
            z.null(),
        ])
        .optional(),
    size: z
        .enum([
            "auto",
            "1024x1024",
            "1536x1024",
            "1024x1536",
            "256x256",
            "512x512",
            "1792x1024",
            "1024x1792",
        ])
        .describe(
            "The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.",
        )
        .default("auto"),
    moderation: z
        .enum(["low", "auto"])
        .describe(
            "Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).",
        )
        .default("auto"),
    background: z
        .enum(["transparent", "opaque", "auto"])
        .describe(
            "Allows to set transparency for the background of the generated image(s).\nThis parameter is only supported for `gpt-image-1`. Must be one of\n`transparent`, `opaque` or `auto` (default value). When `auto` is used, the\nmodel will automatically determine the best background for the image.\n\nIf `transparent`, the output format needs to support transparency, so it\nshould be set to either `png` (default value) or `webp`.\n",
        )
        .default("auto"),
    style: z
        .enum(["vivid", "natural"])
        .describe(
            "The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.",
        )
        .default("vivid"),
    user: z
        .string()
        .describe(
            "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).\n",
        )
        .optional(),
});

const OpenAIEditImageInputSchema = z
    .object({
        image_url: z
            .string()
            .describe("A URL or data URL for a source image used during editing.")
            .optional(),
        file_id: z
            .string()
            .describe("An uploaded provider-managed file id for a source image.")
            .optional(),
    })
    .refine((value) => Boolean(value.image_url || value.file_id), {
        message: "An edited image input requires either image_url or file_id.",
    });

export const OpenAIEditImageSchema = z.object({
    model: z
        .union([z.string(), OpenAIImageModels])
        .describe("The image model to use for editing.")
        .optional(),
    prompt: z.string().describe("A text instruction describing how to edit the source image."),
    images: z
        .array(OpenAIEditImageInputSchema)
        .min(1)
        .describe("One or more source images to edit."),
    size: OpenAICreateImageSchema.shape.size.optional(),
    quality: OpenAICreateImageSchema.shape.quality.optional(),
    response_format: OpenAICreateImageSchema.shape.response_format.optional(),
    output_format: OpenAICreateImageSchema.shape.output_format.optional(),
    output_compression: OpenAICreateImageSchema.shape.output_compression.optional(),
    stream: OpenAICreateImageSchema.shape.stream.optional(),
    partial_images: OpenAICreateImageSchema.shape.partial_images.optional(),
    moderation: OpenAICreateImageSchema.shape.moderation.optional(),
    background: OpenAICreateImageSchema.shape.background.optional(),
    user: OpenAICreateImageSchema.shape.user.optional(),
    input_fidelity: z
        .enum(["high", "low", "auto"])
        .describe("Controls how closely the edit should preserve the source image details.")
        .optional(),
});

export const OpenAICreateImage = z.object({
    created: z
        .number()
        .int()
        .describe("The Unix timestamp (in seconds) of when the image was created."),
    data: z
        .array(
            z
                .object({
                    b64_json: z
                        .string()
                        .describe(
                            "The base64-encoded JSON of the generated image. Default value for `gpt-image-1`, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.",
                        )
                        .optional(),
                    url: z
                        .string()
                        .describe(
                            "When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for `gpt-image-1`.",
                        )
                        .optional(),
                    revised_prompt: z
                        .string()
                        .describe(
                            "For `dall-e-3` only, the revised prompt that was used to generate the image.",
                        )
                        .optional(),
                })
                .describe(
                    "Represents the content or the URL of an image generated by the OpenAI API.",
                ),
        )
        .describe("The list of generated images.")
        .optional(),
    background: z
        .enum(["transparent", "opaque"])
        .describe(
            "The background parameter used for the image generation. Either `transparent` or `opaque`.",
        )
        .optional(),
    output_format: z
        .enum(["png", "webp", "jpeg"])
        .describe("The output format of the image generation. Either `png`, `webp`, or `jpeg`.")
        .optional(),
    size: z
        .enum(["1024x1024", "1024x1536", "1536x1024"])
        .describe(
            "The size of the image generated. Either `1024x1024`, `1024x1536`, or `1536x1024`.",
        )
        .optional(),
    quality: z
        .enum(["low", "medium", "high"])
        .describe("The quality of the image generated. Either `low`, `medium`, or `high`.")
        .optional(),
    usage: z
        .object({
            input_tokens: z
                .number()
                .int()
                .describe("The number of tokens (images and text) in the input prompt."),
            total_tokens: z
                .number()
                .int()
                .describe(
                    "The total number of tokens (images and text) used for the image generation.",
                ),
            output_tokens: z
                .number()
                .int()
                .describe("The number of output tokens generated by the model."),
            input_tokens_details: z
                .object({
                    text_tokens: z
                        .number()
                        .int()
                        .describe("The number of text tokens in the input prompt."),
                    image_tokens: z
                        .number()
                        .int()
                        .describe("The number of image tokens in the input prompt."),
                })
                .describe("The input tokens detailed information for the image generation."),
        })
        .describe("For `gpt-image-1` only, the token usage information for the image generation.")
        .optional(),
});

export type OpenAICreateImageSchema = z.input<typeof OpenAICreateImageSchema>;
export type OpenAICreateImage = z.infer<typeof OpenAICreateImage>;
export type OpenAIEditImageSchema = z.input<typeof OpenAIEditImageSchema>;
