import { z } from "zod";

export const OpenAIEmbeddingModels = z.enum([
    "text-embedding-3-small",
    "text-embedding-3-large",
    "text-embedding-ada-002",
]);

export type OpenAIEmbeddingModels = z.infer<typeof OpenAIEmbeddingModels>;

export const CreateEmbeddingRequest = z.object({
    input: z
        .union([
            z.string().describe("The string that will be turned into an embedding."),
            z
                .array(z.string().default(""))
                .min(1)
                .max(2048)
                .describe("The array of strings that will be turned into an embedding."),
            z
                .array(z.number().int())
                .min(1)
                .max(2048)
                .describe("The array of integers that will be turned into an embedding."),
            z
                .array(z.array(z.number().int()).min(1))
                .min(1)
                .max(2048)
                .describe(
                    "The array of arrays containing integers that will be turned into an embedding.",
                ),
        ])
        .describe(
            "Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model (8192 tokens for all embedding models), cannot be an empty string, and any array must be 2048 dimensions or less. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens. In addition to the per-input token limit, all embedding  models enforce a maximum of 300,000 tokens summed across all inputs in a  single request.\n",
        ),
    model: z
        .union([
            z.string(),
            z.enum(["text-embedding-ada-002", "text-embedding-3-small", "text-embedding-3-large"]),
        ])
        .describe(
            "ID of the model to use. You can use the [List models](https://platform.openai.com/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](https://platform.openai.com/docs/models) for descriptions of them.\n",
        ),
    encoding_format: z
        .enum(["float", "base64"])
        .describe(
            "The format to return the embeddings in. Can be either `float` or [`base64`](https://pypi.org/project/pybase64/).",
        )
        .default("float"),
    dimensions: z
        .number()
        .int()
        .gte(1)
        .describe(
            "The number of dimensions the resulting output embeddings should have. Only supported in `text-embedding-3` and later models.\n",
        )
        .optional(),
    user: z
        .string()
        .describe(
            "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).\n",
        )
        .optional(),
});

export const CreateEmbeddingResponse = z.object({
    data: z
        .array(
            z
                .object({
                    index: z
                        .number()
                        .int()
                        .describe("The index of the embedding in the list of embeddings."),
                    embedding: z
                        .array(z.number())
                        .describe(
                            "The embedding vector, which is a list of floats. The length of vector depends on the model as listed in the [embedding guide](https://platform.openai.com/docs/guides/embeddings).\n",
                        ),
                    object: z
                        .literal("embedding")
                        .describe('The object type, which is always "embedding".'),
                })
                .describe("Represents an embedding vector returned by embedding endpoint.\n"),
        )
        .describe("The list of embeddings generated by the model."),
    model: z.string().describe("The name of the model used to generate the embedding."),
    object: z.literal("list").describe('The object type, which is always "list".'),
    usage: z
        .object({
            prompt_tokens: z.number().int().describe("The number of tokens used by the prompt."),
            total_tokens: z
                .number()
                .int()
                .describe("The total number of tokens used by the request."),
        })
        .describe("The usage information for the request."),
});

export type OpenAICreateEmbeddingRequest = z.input<typeof CreateEmbeddingRequest>;
export type OpenAICreateEmbeddingResponse = z.infer<typeof CreateEmbeddingResponse>;
