/**
 * Event name constants emitted by the runtime.
 */
export const Events = {
    RUN_STARTED: "RUN_STARTED",
    RUN_FINISHED: "RUN_FINISHED",
    RUN_ERROR: "RUN_ERROR",
    RUN_ABORTED: "RUN_ABORTED",

    // User-defined runtime data payload.
    DATA_PART: "DATA_PART",

    STEP_START: "STEP_START",
    STEP_FINISH: "STEP_FINISH",
    STEP_ERROR: "STEP_ERROR",

    TOOL_CALL_START: "TOOL_CALL_START",
    TOOL_CALL_ARGS: "TOOL_CALL_ARGS",
    TOOL_CALL_END: "TOOL_CALL_END",
    TOOL_CALL_RESULT: "TOOL_CALL_RESULT",

    TOOL_APPROVAL_REQUIRED: "TOOL_APPROVAL_REQUIRED",
    TOOL_APPROVAL_UPDATED: "TOOL_APPROVAL_UPDATED",

    TEXT_MESSAGE_START: "TEXT_MESSAGE_START",
    TEXT_MESSAGE_CONTENT: "TEXT_MESSAGE_CONTENT",
    TEXT_MESSAGE_END: "TEXT_MESSAGE_END",

    IMAGE_MESSAGE_START: "IMAGE_MESSAGE_START",
    IMAGE_MESSAGE_CONTENT: "IMAGE_MESSAGE_CONTENT",
    IMAGE_MESSAGE_END: "IMAGE_MESSAGE_END",

    VIDEO_MESSAGE_START: "VIDEO_MESSAGE_START",
    VIDEO_MESSAGE_CONTENT: "VIDEO_MESSAGE_CONTENT",
    VIDEO_MESSAGE_END: "VIDEO_MESSAGE_END",

    AUDIO_MESSAGE_START: "AUDIO_MESSAGE_START",
    AUDIO_MESSAGE_CONTENT: "AUDIO_MESSAGE_CONTENT",
    AUDIO_MESSAGE_END: "AUDIO_MESSAGE_END",

    TRANSCRIPT_MESSAGE_START: "TRANSCRIPT_MESSAGE_START",
    TRANSCRIPT_MESSAGE_CONTENT: "TRANSCRIPT_MESSAGE_CONTENT",
    // Finalized transcript segment.
    TRANSCRIPT_MESSAGE_SEGMENT: "TRANSCRIPT_MESSAGE_SEGMENT",
    TRANSCRIPT_MESSAGE_END: "TRANSCRIPT_MESSAGE_END",

    REASONING_MESSAGE_START: "REASONING_MESSAGE_START",
    REASONING_MESSAGE_CONTENT: "REASONING_MESSAGE_CONTENT",
    REASONING_MESSAGE_END: "REASONING_MESSAGE_END",

    EMBEDDING_MESSAGE_START: "EMBEDDING_MESSAGE_START",
    EMBEDDING_MESSAGE_CONTENT: "EMBEDDING_MESSAGE_CONTENT",
    EMBEDDING_MESSAGE_END: "EMBEDDING_MESSAGE_END",
} as const;

/**
 * Union of all event names.
 */
export type EventName = (typeof Events)[keyof typeof Events];
